export const metadat = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
